<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="werdna">
    
    <xacro:include filename="consts.xacro"/>  
    <xacro:include filename='inertial_macros.xacro'/>

    <!-- *********** base link *********** -->
    <link name="base_link"></link>

    <!-- CHASSIS -->

    <link name="chassis_link">
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </collision>
    </link>

    <!-- chassis_joint -->
    <joint name="chassis_joint" type="fixed">
        <origin xyz="0.0 0.0 ${chassis_height/2}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="chassis_link"/>
    </joint>

    <!-- imu -->
    <link name="imu_link">
        <xacro:inertial_box mass="${imu_mass}" x="${imu_length}" y="${imu_width}" z="${imu_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}"/>
            </geometry>
            <material name="white"/>
        </collision>
    </link>

    <!-- imu joint -->
    <joint name="imu_joint" type="fixed">
        <origin xyz="0.0 0.0 ${chassis_height/2 + imu_height/2}" rpy="0.0 0.0 0.0"/>
        <parent link="chassis_link"/>
        <child link="imu_link"/>
    </joint>

    <!-- LEFT HIP MOTOR -->
    <link name="left_hip_motor_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${motor_radius}" length="${motor_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${motor_radius}" length="${motor_thickness}"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_cylinder mass="${motor_mass}" length="${motor_thickness}" radius="${motor_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="left_hip_motor_joint" type="revolute">
        <origin xyz="0.0 ${chassis_width/2 + motor_thickness/2} 0.0" rpy="${pi/2} -0.6897975409348593 0.0"/>
        <parent link="chassis_link"/>
        <child link="left_hip_motor_link"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="${low_limit}" upper="${high_limit}" velocity="${velocity}" effort="${effort}"/>
    </joint>

    <!-- LEFT HIP ROD -->
    <link name="left_hip_link">
        <visual>
            <origin xyz="-${rod_height/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="-${rod_height/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
            <origin xyz="-${rod_height/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="left_hip_joint" type="fixed">
        <origin xyz="0.0 0.0 -${motor_thickness/2 + rod_length/2}" rpy="0.0 0.0 0.0"/>
        <parent link="left_hip_motor_link"/>
        <child link="left_hip_link"/>
    </joint>

    <!-- LEFT KNEE MOTOR -->
    <link name="left_knee_motor_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${motor_radius}" length="${motor_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${motor_radius}" length="${motor_thickness}"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_cylinder mass="${motor_mass}" length="${motor_thickness}" radius="${motor_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="left_knee_motor_joint" type="revolute">
        <origin xyz="-${rod_height} 0 -${motor_thickness/2 + rod_length/2}" rpy="0.0 0 -1.1336790410021163"/>
        <parent link="left_hip_link"/>
        <child link="left_knee_motor_link"/>
        <axis xyz="0.0 0.0 -1.0"/>
        <limit lower="${low_limit}" upper="${high_limit}" velocity="${velocity}" effort="${effort}"/>
    </joint>

    <!-- LEFT KNEE ROD -->
    <link name="left_knee_link">
        <visual>
            <origin xyz="0 0 ${rod_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${rod_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
            <origin xyz="0 0 ${rod_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="left_knee_joint" type="fixed">
        <origin xyz="0 0 -${motor_thickness/2 + rod_length/2}" rpy="0.0 ${pi/2} 0.0"/>
        <parent link="left_knee_motor_link"/>
        <child link="left_knee_link"/>
    </joint>

    <!-- LEFT WHEEL -->
    <link name="left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="left_wheel_joint" type="continuous">
      <origin xyz="${rod_length/2 + wheel_length/2} 0 ${rod_height}" rpy="0 ${pi/2} 0"/>
      <parent link="left_knee_link"/>
      <child link="left_wheel"/>
      <axis xyz="0.0 0.0 1.0"/>
    </joint>


    <!-- RIGHT HIP MOTOR -->
    <link name="right_hip_motor_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${motor_radius}" length="${motor_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${motor_radius}" length="${motor_thickness}"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_cylinder mass="${motor_mass}" length="${motor_thickness}" radius="${motor_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="right_hip_motor_joint" type="revolute">
        <origin xyz="0.0 -${chassis_width/2 + motor_thickness/2} 0.0" rpy="${pi/2} -0.6897975409348593 0.0"/>
        <parent link="chassis_link"/>
        <child link="right_hip_motor_link"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="${low_limit}" upper="${high_limit}" velocity="${velocity}" effort="${effort}"/>
    </joint>

    <!-- RIGHT HIP LINK -->
    <link name="right_hip_link">
        <visual>
            <origin xyz="-${rod_height/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="-${rod_height/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
            <origin xyz="-${rod_height/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="right_hip_joint" type="fixed">
        <origin xyz="0.0 0.0 ${motor_thickness/2 + rod_length/2}" rpy="0.0 0.0 0.0"/>
        <parent link="right_hip_motor_link"/>
        <child link="right_hip_link"/>
    </joint>

    <!-- RIGHT KNEE MOTOR -->
    <link name="right_knee_motor_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${motor_radius}" length="${motor_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${motor_radius}" length="${motor_thickness}"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_cylinder mass="${motor_mass}" length="${motor_thickness}" radius="${motor_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="right_knee_motor_joint" type="revolute">
        <origin xyz="-${rod_height} 0 ${motor_thickness/2 + rod_length/2}" rpy="0.0 0 -1.1336790410021163"/>
        <parent link="right_hip_link"/>
        <child link="right_knee_motor_link"/>
        <axis xyz="0.0 0.0 -1.0"/>
        <limit lower="${low_limit}" upper="${high_limit}" velocity="${velocity}" effort="${effort}"/>
    </joint>

    <!-- RIGHT KNEE ROD -->
    <link name="right_knee_link">
        <visual>
            <origin xyz="0 0 ${rod_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${rod_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
            <origin xyz="0 0 ${rod_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="right_knee_joint" type="fixed">
        <origin xyz="0 0 ${motor_thickness/2 + rod_length/2}" rpy="0.0 ${pi/2} 0.0"/>
        <parent link="right_knee_motor_link"/>
        <child link="right_knee_link"/>
    </joint>

    <!-- RIGHT WHEEL -->
    <link name="right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="right_wheel_joint" type="continuous">
      <origin xyz="-${rod_length/2 + wheel_length/2} 0 ${rod_height}" rpy="0 ${pi/2} 0"/>
      <parent link="right_knee_link"/>
      <child link="right_wheel"/>
      <axis xyz="0.0 0.0 1.0"/>
    </joint>


</robot>
